-- AlterTable
ALTER TABLE "Agent" ADD COLUMN     "maxTokens" INTEGER NOT NULL DEFAULT 1024,
ADD COLUMN     "memorySize" INTEGER NOT NULL DEFAULT 3,
ADD COLUMN     "temperature" DOUBLE PRECISION NOT NULL DEFAULT 0;
